### ISSUE TITLE
Angular velocity not in public library

### ISSUE THREAD

**Issue by bnlerner** [adafruit/Adafruit_CircuitPython_BNO08x_RVC#10]
I purchased [Adafruit 9-DOF Orientation IMU Fusion Breakout - BNO085](https://www.adafruit.com/product/4754) which claims to give angular velocity. There does not appear to be a way to get this from the current output in this library via .heading. Is there other libraries that enable this or something im missing here

**Comment by caternuson** [comment]
RVC mode is a special simplified mode that only outputs acceleration and heading:
![image](https://github.com/user-attachments/assets/9dac58d8-52de-4415-ba17-b373b4841dd5)

For angular velocity, use this other library:
https://github.com/adafruit/Adafruit_CircuitPython_BNO08x

**Comment by bnlerner** [comment]
Thank you!
